export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
export const CHANGE_MODE = 'CHANGE_MODE';
export const SELECT_AUTHOR = 'SELECT_AUTHOR';
export const SHOW_AUTHOR_COMMENTS = 'SHOW_AUTHOR_COMMENTS';
